version: '3.7'
services:
  web:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    networks:
      - backend

networks:
  backend:
  default:
    external:
      name: backend
