version: '3.7'
services:
  web:
    container_name: client2
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - backend

networks:
  backend:
  default:
    external:
      name: backend
