// global state
export const GLOBAL_STATE = 'x-state'

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOG_OUT = 'USER_LOG_OUT'

export const GET_ARTICLES = 'GET_ARTICLE'
export const GET_ARTICLE_ERROR = 'GET_ARTICLE_ERROR'
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR'

export const SEARCH_ARTICLE = 'SEARCH_ARTICLE'
export const SEARCH_ARTICLE_ERROR = 'SEARCH_ARTICLE_ERROR'

export const FILTER_ARTICLE = 'FILTER_ARTICLE'
